import type { ConsoleEvent } from "@/lib/events";

const responder = { id: "responder-01", region: "us-east" } as const;

export const PHASE_TWO_EVENTS: readonly ConsoleEvent[] = [
  {
    id: "evt-001",
    sequence: 1,
    occurredAt: "2026-07-30T03:01:00.000Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "incident",
    payload: {
      service: "checkout-api",
      severity: "SEV-1",
      status: "open",
      summary: "p99 latency 4.2s · error rate 18.4% after deploy #5120",
      telemetry: {
        p99LatencyMs: 4200,
        errorRatePct: 18.4,
        deploy: "#5120",
        errorBudgetBurnRate: 16.2,
      },
    },
  },
  {
    id: "evt-002",
    sequence: 2,
    occurredAt: "2026-07-30T03:01:03.184Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "recall",
    payload: {
      querySummary: "checkout p99 spike after canary deploy",
      provider: "c-spann+mcp",
      durationMs: 184,
      results: [
        {
          memoryId: "ep-8842",
          memoryKind: "episodic",
          sourceCaseId: "CASE-1878",
          summary: "Checkout p99 spike after canary deploy #4471",
          similarity: 0.94,
          accepted: true,
          confidence: 0.96,
          successRate: 0.9,
          score: {
            vector: 0.94,
            scope: 1,
            freshness: 0.82,
            outcome: 0.9,
            composite: 0.92,
          },
          provenance: ["CASE-1878", "RB-207"],
          runbookId: "RB-207",
          successfulAction: "Rollback canary; scaling increased queue contention",
          scope: { service: "checkout-api", tenant: "demo-org" },
          validFrom: "2026-03-14T02:16:00.000Z",
          learnedAt: "2026-03-14T02:31:00.000Z",
        },
        {
          memoryId: "fact-2201",
          memoryKind: "semantic",
          sourceCaseId: "CASE-1878",
          summary: "checkout-api safe rollback target is the previous stable deploy",
          similarity: 0.88,
          accepted: true,
          confidence: 0.93,
          score: {
            vector: 0.88,
            scope: 1,
            freshness: 0.91,
            outcome: 0.8,
            composite: 0.89,
          },
          provenance: ["CASE-1878"],
          scope: { service: "checkout-api", tenant: "demo-org" },
          validFrom: "2026-06-12T08:00:00.000Z",
          learnedAt: "2026-06-12T08:01:00.000Z",
        },
        {
          memoryId: "RB-207",
          memoryKind: "procedural",
          sourceCaseId: "CASE-1878",
          summary: "Rollback a canary when the error-rate onset correlates with its deploy.",
          similarity: 0.92,
          accepted: true,
          confidence: 0.95,
          successRate: 0.9,
          score: {
            vector: 0.92,
            scope: 1,
            freshness: 0.86,
            outcome: 0.9,
            composite: 0.93,
          },
          provenance: ["CASE-1878", "CASE-1931", "CASE-1998"],
          runbookId: "RB-207",
          successfulAction: "Rollback canary",
          scope: { service: "checkout-api", tenant: "demo-org" },
          validFrom: "2026-03-14T02:31:00.000Z",
          learnedAt: "2026-06-28T10:20:00.000Z",
        },
      ],
      mode: "memory",
      rejectedCount: 4,
    },
  },
  {
    id: "evt-003",
    sequence: 3,
    occurredAt: "2026-07-30T03:01:04.430Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "reason",
    payload: {
      message:
        "I’ve seen this failure shape before. CASE-1878 is a 0.94 match: scaling increased contention; rolling back the canary restored the SLO. I recommend rollback to #5119.",
      citedMemoryIds: ["ep-8842"],
      citedRunbookIds: ["RB-207"],
    },
  },
  {
    id: "evt-004",
    sequence: 4,
    occurredAt: "2026-07-30T03:01:05.000Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "act",
    payload: {
      actionId: "act-5120-rollback",
      status: "proposed",
      tool: "remediate_and_record",
      arguments: {
        service: "checkout-api",
        fromDeploy: 5120,
        toDeploy: 5119,
      },
      target: "deploys/checkout-api",
      requiresApproval: true,
      citedMemoryId: "ep-8842",
    },
  },
  {
    id: "evt-005",
    sequence: 5,
    occurredAt: "2026-07-30T03:02:11.470Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "transaction",
    payload: {
      transactionId: "8f2ab471c90e",
      state: "committed",
      committedAt: "2026-07-30T03:02:11.470Z",
      statements: [
        {
          operation: "UPDATE",
          target: "deploys",
          role: "action",
          summary: "activate #5119 · retire #5120",
        },
        {
          operation: "INSERT",
          target: "remediation_actions",
          role: "audit",
          summary: "rollback · outcome=pending_verification",
        },
        {
          operation: "INSERT",
          target: "episodic_events",
          role: "memory",
          summary: "action outcome · provenance=ep-8842",
        },
      ],
    },
  },
  {
    id: "evt-006",
    sequence: 6,
    occurredAt: "2026-07-30T03:02:11.510Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "record",
    payload: {
      memoryId: "ep-9217",
      memoryKind: "episodic",
      summary: "Rollback #5120 → #5119 committed with action act-5120-rollback",
      freshnessMs: 40,
      recalledBy: { id: "responder-02", region: "eu-west" },
      staleReadsObserved: 0,
    },
  },
  {
    id: "evt-007",
    sequence: 7,
    occurredAt: "2026-07-30T03:02:12.000Z",
    caseId: "CASE-2041",
    agent: responder,
    type: "evaluation",
    payload: {
      seed: 20260730,
      // Real, measured retrieval numbers (offline replay mirrors the v2 report).
      retrieval: {
        recallAt1: 0.85,
        recallAt5: 1.0,
        recallAt10: 1.0,
        ndcgAt10: 0.94,
        hardNegativeCount: 9,
      },
      // Decision quality is NOT measured yet (needs the real agent).
      decisionQualityMeasured: false,
    },
  },
];

export const MOCK_EVENT_INTERVAL_MS = 560;
