FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY postmortem_consolidation ${LAMBDA_TASK_ROOT}/postmortem_consolidation

CMD ["postmortem_consolidation.handlers.consolidator_handler"]
